apiVersion : apps/v1
kind: Deployment
metadata:
  name: embloyembloycoreclient 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embloyembloycoreclient
  template:
    metadata:
      labels:
        app: embloyembloycoreclient 
    spec:
      containers:
        - name: embloyembloycoreclient 
          image: embloy.azurecr.io/embloyembloycoreclient
          ports:
          - containerPort: 3000